<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions 
	name="PartyRoleTypeService" 
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" 
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" 
	xmlns:pp="http://www.processpuzzle.com"
	targetNamespace="http://www.processpuzzle.com">
  <wsdl:types>
  </wsdl:types>
  
  <wsdl:message name="FindByIdRequest">
	<wsdl:part name="id" type="xsd:integer" />
  </wsdl:message>

  <wsdl:message name="FindByIdResponse">
	<wsdl:part name="workProduct" type="xsd:string" />
  </wsdl:message>

  <wsdl:portType name="PartyRoleTypeService">
    <wsdl:operation name="findById">
      <wsdl:input message="pp:FindByIdRequest"/>
      <wsdl:output message="pp:FindByIdResponse"/>
    </wsdl:operation>
  </wsdl:portType>
  
  <wsdl:binding name="PartyRoleTypeService" type="pp:PartyRoleTypeService">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    
    <wsdl:operation name="findById">
      <soap:operation soapAction="http://www.processpuzzle.com/PartyRoleTypeService/findById"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  
  <wsdl:service name="PartyRoleTypeService">
    <wsdl:port name="PartyRoleTypeService" binding="pp:PartyRoleTypeService" >
      <soap:address location="http://localhost:8080/ProcessPuzzle" />
    </wsdl:port>
  </wsdl:service>
  
</wsdl:definitions>