--<ScriptOptions statementTerminator=";"/>

CREATE TABLE T_USER (
		ID INTEGER NOT NULL,
		VERSION INTEGER,
		USERNAME VARCHAR(255),
		PASSWORD VARCHAR(255),
		LOCATION VARCHAR(255),
		LANGUAGE VARCHAR(255),
		COUNTRY VARCHAR(255)
	);

CREATE TABLE T_USER_DATA_SHEET (
		ID INTEGER NOT NULL,
		VERSION INTEGER,
		NAME VARCHAR(255),
		PATH VARCHAR(255),
		ARTIFACT_FOLDER_ID INTEGER,
		TYPE INTEGER,
		ARTIFACT_VERSION_ID INTEGER,
		USER INTEGER
	);

CREATE TABLE T_USER_LIST (
		ID INTEGER NOT NULL,
		VERSION INTEGER,
		NAME VARCHAR(255),
		PATH VARCHAR(255),
		ARTIFACT_FOLDER_ID INTEGER,
		TYPE INTEGER,
		ARTIFACT_VERSION_ID INTEGER
	);

CREATE TABLE HIBERNATE_UNIQUE_KEY (
		NEXT_HI INTEGER
	);

CREATE TABLE T_ACCESS_RIGHT (
		ID INTEGER NOT NULL,
		VERSION INTEGER,
		CANREAD null,
		CANCREATE null,
		CANMODIFY null,
		CANDELETE null,
		USERROLENAME VARCHAR(255),
		ARTIFACT_TYPE_GROUP_ID INTEGER,
		ARTIFACT_TYPE_ID INTEGER,
		CONTROLLEDOBJECTID INTEGER,
		CONTROLLEDOBJECTCLASS VARCHAR(255),
		USER_ID INTEGER
	);

CREATE TABLE T_APPLICATION_EVENT (
		ID INTEGER NOT NULL,
		VERSION INTEGER,
		EVENTDESCRIPTION VARCHAR(255),
		TIMESTAMP TIMESTAMP
	);

CREATE TABLE T_ARTIFACT_ACCESSRIGHTS_VIEW_TYPE (
		ARTIFACT_ACCESSRIGHTS_VIEW_TYPE_ID INTEGER NOT NULL
	);

CREATE TABLE T_ARTIFACT_COMMENTS_VIEW_TYPE (
		ARTIFACT_COMMENTS_VIEW_TYPE_ID INTEGER NOT NULL
	);

CREATE TABLE T_ARTIFACT_CUSTOMFORM_VIEW_TYPE (
		ARTIFACT_CUSTOMFORM_VIEW_TYPE_ID INTEGER NOT NULL
	);

CREATE TABLE T_ARTIFACT_EDITABLETEXT_VIEW_TYPE (
		ARTIFACT_EDITABLETEXT_VIEW_TYPE_ID INTEGER NOT NULL,
		XMLTOHTMLXSLTPATH VARCHAR(255)
	);

CREATE TABLE T_ARTIFACT_FOLDER (
		ID INTEGER NOT NULL,
		VERSION INTEGER,
		NAME VARCHAR(255),
		PATH VARCHAR(255),
		ARTIFACT_FOLDER_ID INTEGER,
		TYPE INTEGER,
		ARTIFACT_VERSION_ID INTEGER
	);

CREATE TABLE T_ARTIFACT_LIST (
		ID INTEGER NOT NULL,
		VERSION INTEGER,
		NAME VARCHAR(255),
		PATH VARCHAR(255),
		ARTIFACT_FOLDER_ID INTEGER,
		TYPE INTEGER,
		ARTIFACT_VERSION_ID INTEGER
	);

CREATE TABLE T_ARTIFACT_LIST_VIEW_TYPE (
		ARTIFACT_LIST_VIEW_TYPE_ID INTEGER NOT NULL,
		LISTEDARTIFACTTYPE VARCHAR(255),
		ORDERBY VARCHAR(255),
		ORD VARCHAR(255)
	);

CREATE TABLE T_ARTIFACT_MENU (
		ID INTEGER NOT NULL,
		VERSION INTEGER,
		NAME VARCHAR(255),
		COMMAND INTEGER,
		ARTIFACT_VIEW_TYPE_ID INTEGER,
		ARTIFACT_TYPE_ID INTEGER
	);

CREATE TABLE T_ARTIFACT_MENU_COMMAND (
		ID INTEGER NOT NULL,
		VERSION INTEGER,
		NAME VARCHAR(255),
		DESCRIPTION VARCHAR(255),
		TYPE VARBINARY,
		ACTIONSTATEMENT VARCHAR(255),
		CUSTOMPREFIX VARCHAR(255)
	);

CREATE TABLE T_ARTIFACT_MODIFICATIONS_VIEW_TYPE (
		ARTIFACT_MODIFICATIONS_VIEW_TYPE_ID INTEGER NOT NULL
	);

CREATE TABLE T_ARTIFACT_PRINT_VIEW_TYPE (
		ARTIFACT_PRINT_VIEW_TYPE_ID INTEGER NOT NULL,
		XMLTOFOXSLTPATH VARCHAR(255)
	);

CREATE TABLE T_ARTIFACT_PROPERTY_VIEW_TYPE (
		RELATED_ARTIFACTS_VIEW_TYPE_ID INTEGER NOT NULL
	);

CREATE TABLE T_ARTIFACT_TYPE (
		ID INTEGER NOT NULL,
		VERSION INTEGER,
		NAME VARCHAR(255),
		DESCRIPTION VARCHAR(255),
		ARTIFACTCLASSNAME VARCHAR(255),
		DOMAINCLASSNAME VARCHAR(255),
		INSTANCEFOLDER VARCHAR(255),
		CAPTION VARCHAR(255),
		BASEURI VARCHAR(255),
		ISSYSTEM null,
		CREATEONSTARTUP null,
		ISSINGLETON null,
		PESSIMISTICLOCK null,
		ISVERSIONCONTROLLED null,
		REFRESHONDOCUMENTACTIVATION null,
		REFRESHONVIEWACTIVATION null,
		ARTIFACT_TYPE_GROUP_ID INTEGER
	);

CREATE TABLE T_ARTIFACT_TYPE_GROUP (
		ID INTEGER NOT NULL,
		VERSION INTEGER,
		NAME VARCHAR(255)
	);

CREATE TABLE T_ARTIFACT_VERSION (
		ARTIFACT_VERSION_ID INTEGER NOT NULL,
		NAME VARCHAR(255),
		CREATION TIMESTAMP,
		MODIFICATION TIMESTAMP,
		RESPONSIBLE INTEGER,
		ISVERSIONCONTROLLED null,
		CONTAININGFOLDER INTEGER,
		NEXTMODIFICATION INTEGER,
		ARTIFACT_ID INTEGER,
		VERSION_NUMBER_KEY INTEGER
	);

CREATE TABLE T_ARTIFACT_VIEW_TYPE (
		ARTIFACT_VIEW_TYPE_ID INTEGER NOT NULL,
		NAME VARCHAR(255),
		CLIENTTYPE VARCHAR(255),
		VIEWCLASSNAME VARCHAR(255),
		ISDEFAULT null,
		ISSTATIC null,
		VIEWCAPTION VARCHAR(255),
		VIEWACCESSURL VARCHAR(255),
		PRESENTATIONURI VARCHAR(255),
		ARTIFACT_TYPE_ID INTEGER
	);

CREATE TABLE T_AUTO_IDENTIFIER (
		ID INTEGER NOT NULL,
		VERSION INTEGER,
		QUALIFIER VARCHAR(255),
		YEAR INTEGER,
		CNT INTEGER,
		IDTYPE VARCHAR(255)
	);

CREATE TABLE T_BACKUP_EVENT (
		ID INTEGER NOT NULL,
		VERSION INTEGER,
		EVENTDESCRIPTION VARCHAR(255),
		TIMESTAMP TIMESTAMP
	);

CREATE TABLE T_DEFAULT_ACCESS_RIGHT (
		ID INTEGER NOT NULL,
		VERSION INTEGER,
		CANREAD null,
		CANCREATE null,
		CANMODIFY null,
		CANDELETE null,
		USERROLENAME VARCHAR(255),
		ARTIFACT_TYPE_GROUP_ID INTEGER,
		ARTIFACT_TYPE_ID INTEGER
	);

CREATE TABLE T_HTML_ATTRIBUTE_FORMAT (
		HTML_ATTRIBUTE_FORMAT_ID INTEGER NOT NULL,
		TARGETPROPERTY VARCHAR(255),
		HTMLELEMENTNAME VARCHAR(255),
		STARTINDEX INTEGER,
		ENDINDEX INTEGER,
		ARTIFACT_ID INTEGER
	);

CREATE TABLE T_LAST_ID_NUMBER (
		ID INTEGER NOT NULL,
		VERSION INTEGER,
		IDTYPE VARCHAR(255) NOT NULL,
		LATESTNUMBER INTEGER NOT NULL
	);

CREATE TABLE T_LIST_QUERY_VIEW_TYPE (
		LIST_QUERY_VIEW_TYPE_ID INTEGER NOT NULL,
		TARGETPROPERTYVIEW VARCHAR(255)
	);

CREATE TABLE T_MODIFICATION (
		MODIFICATION_ID INTEGER NOT NULL,
		STATUS VARCHAR(255),
		COMMENT VARCHAR(255),
		BEGIN_VALUE TIMESTAMP,
		END_VALUE TIMESTAMP,
		MODIFIER INTEGER,
		TARGETVERSION INTEGER
	);

CREATE TABLE T_PROPERTY_DEFINITION (
		ID INTEGER NOT NULL,
		VERSION INTEGER,
		NAME VARCHAR(255),
		TYPE VARBINARY,
		VALUE VARCHAR(255),
		ARTIFACT_TYPE_ID INTEGER
	);

CREATE TABLE T_QUERY (
		QUERY_ID INTEGER NOT NULL,
		NAME VARCHAR(255),
		DESCRIPTION VARCHAR(255),
		PREDEFINEDSTATEMENT VARCHAR(255),
		LIST_QUERY_VIEW_TYPE_ID INTEGER
	);

CREATE TABLE T_RELATED_ARTIFACTS_VIEW_TYPE (
		RELATED_ARTIFACTS_VIEW_TYPE_ID INTEGER NOT NULL
	);

CREATE TABLE T_ROOT_ARTIFACT_FOLDER (
		ID INTEGER NOT NULL,
		VERSION INTEGER,
		NAME VARCHAR(255),
		PATH VARCHAR(255),
		ARTIFACT_FOLDER_ID INTEGER,
		TYPE INTEGER,
		ARTIFACT_VERSION_ID INTEGER
	);

CREATE INDEX SYS_IDX_10209 ON T_MODIFICATION (TARGETVERSION ASC);

CREATE INDEX SYS_IDX_10167 ON T_ARTIFACT_COMMENTS_VIEW_TYPE (ARTIFACT_COMMENTS_VIEW_TYPE_ID ASC);

CREATE UNIQUE INDEX SYS_IDX_SYS_PK_10086_10087 ON T_ARTIFACT_LIST (ID ASC);

CREATE UNIQUE INDEX SYS_IDX_SYS_PK_10110_10111 ON T_ARTIFACT_TYPE_GROUP (ID ASC);

CREATE INDEX SYS_IDX_10211 ON T_MODIFICATION (MODIFIER ASC);

CREATE UNIQUE INDEX SYS_IDX_SYS_PK_10125_10126 ON T_HTML_ATTRIBUTE_FORMAT (HTML_ATTRIBUTE_FORMAT_ID ASC);

CREATE INDEX SYS_IDX_10177 ON T_ARTIFACT_LIST (ARTIFACT_VERSION_ID ASC);

CREATE INDEX SYS_IDX_10179 ON T_ARTIFACT_LIST (TYPE ASC);

CREATE UNIQUE INDEX SYS_IDX_SYS_PK_10138_10139 ON T_PROPERTY_DEFINITION (ID ASC);

CREATE INDEX SYS_IDX_10159 ON T_ACCESS_RIGHT (ARTIFACT_TYPE_ID ASC);

CREATE UNIQUE INDEX SYS_IDX_SYS_PK_10104_10105 ON T_ARTIFACT_PROPERTY_VIEW_TYPE (RELATED_ARTIFACTS_VIEW_TYPE_ID ASC);

CREATE UNIQUE INDEX SYS_IDX_SYS_PK_10083_10084 ON T_ARTIFACT_FOLDER (ID ASC);

CREATE INDEX SYS_IDX_10213 ON T_PROPERTY_DEFINITION (ARTIFACT_TYPE_ID ASC);

CREATE UNIQUE INDEX SYS_IDX_SYS_PK_10117_10118 ON T_AUTO_IDENTIFIER (ID ASC);

CREATE INDEX SYS_IDX_10161 ON T_ACCESS_RIGHT (USER_ID ASC);

CREATE INDEX SYS_IDX_10193 ON T_ARTIFACT_PROPERTY_VIEW_TYPE (RELATED_ARTIFACTS_VIEW_TYPE_ID ASC);

CREATE INDEX SYS_IDX_10173 ON T_ARTIFACT_FOLDER (ARTIFACT_VERSION_ID ASC);

CREATE INDEX SYS_IDX_10163 ON T_ACCESS_RIGHT (ARTIFACT_TYPE_GROUP_ID ASC);

CREATE UNIQUE INDEX SYS_IDX_SYS_PK_10149_10150 ON T_USER (ID ASC);

CREATE INDEX SYS_IDX_10175 ON T_ARTIFACT_FOLDER (TYPE ASC);

CREATE UNIQUE INDEX SYS_IDX_SYS_PK_10071_10072 ON T_ARTIFACT_ACCESSRIGHTS_VIEW_TYPE (ARTIFACT_ACCESSRIGHTS_VIEW_TYPE_ID ASC);

CREATE UNIQUE INDEX SYS_IDX_SYS_PK_10068_10069 ON T_APPLICATION_EVENT (ID ASC);

CREATE INDEX SYS_IDX_10165 ON T_ARTIFACT_ACCESSRIGHTS_VIEW_TYPE (ARTIFACT_ACCESSRIGHTS_VIEW_TYPE_ID ASC);

CREATE UNIQUE INDEX SYS_IDX_SYS_PK_10114_10115 ON T_ARTIFACT_VIEW_TYPE (ARTIFACT_VIEW_TYPE_ID ASC);

CREATE UNIQUE INDEX SYS_IDX_SYS_PK_10101_10102 ON T_ARTIFACT_PRINT_VIEW_TYPE (ARTIFACT_PRINT_VIEW_TYPE_ID ASC);

CREATE INDEX SYS_IDX_10201 ON T_ARTIFACT_VIEW_TYPE (ARTIFACT_TYPE_ID ASC);

CREATE INDEX SYS_IDX_10191 ON T_ARTIFACT_PRINT_VIEW_TYPE (ARTIFACT_PRINT_VIEW_TYPE_ID ASC);

CREATE UNIQUE INDEX SYS_IDX_SYS_PK_10080_10081 ON T_ARTIFACT_EDITABLETEXT_VIEW_TYPE (ARTIFACT_EDITABLETEXT_VIEW_TYPE_ID ASC);

CREATE UNIQUE INDEX SYS_IDX_SYS_PK_10112_10113 ON T_ARTIFACT_VERSION (ARTIFACT_VERSION_ID ASC);

CREATE UNIQUE INDEX SYS_IDX_SYS_CT_10153_10155 ON T_USER_DATA_SHEET (USER ASC);

CREATE UNIQUE INDEX SYS_IDX_SYS_PK_10123_10124 ON T_DEFAULT_ACCESS_RIGHT (ID ASC);

CREATE INDEX SYS_IDX_10171 ON T_ARTIFACT_EDITABLETEXT_VIEW_TYPE (ARTIFACT_EDITABLETEXT_VIEW_TYPE_ID ASC);

CREATE INDEX SYS_IDX_10197 ON T_ARTIFACT_VERSION (RESPONSIBLE ASC);

CREATE UNIQUE INDEX SYS_IDX_SYS_PK_10152_10154 ON T_USER_DATA_SHEET (ID ASC);

CREATE UNIQUE INDEX SYS_IDX_SYS_PK_10143_10144 ON T_RELATED_ARTIFACTS_VIEW_TYPE (RELATED_ARTIFACTS_VIEW_TYPE_ID ASC);

CREATE INDEX SYS_IDX_10203 ON T_DEFAULT_ACCESS_RIGHT (ARTIFACT_TYPE_ID ASC);

CREATE UNIQUE INDEX SYS_IDX_SYS_PK_10095_10096 ON T_ARTIFACT_MENU_COMMAND (ID ASC);

CREATE INDEX SYS_IDX_10199 ON T_ARTIFACT_VERSION (NEXTMODIFICATION ASC);

CREATE UNIQUE INDEX SYS_IDX_SYS_PK_10140_10141 ON T_QUERY (QUERY_ID ASC);

CREATE INDEX SYS_IDX_10223 ON T_USER_DATA_SHEET (ARTIFACT_VERSION_ID ASC);

CREATE INDEX SYS_IDX_10205 ON T_DEFAULT_ACCESS_RIGHT (ARTIFACT_TYPE_GROUP_ID ASC);

CREATE INDEX SYS_IDX_10217 ON T_RELATED_ARTIFACTS_VIEW_TYPE (RELATED_ARTIFACTS_VIEW_TYPE_ID ASC);

CREATE UNIQUE INDEX SYS_IDX_SYS_PK_10077_10078 ON T_ARTIFACT_CUSTOMFORM_VIEW_TYPE (ARTIFACT_CUSTOMFORM_VIEW_TYPE_ID ASC);

CREATE INDEX SYS_IDX_10225 ON T_USER_DATA_SHEET (TYPE ASC);

CREATE INDEX SYS_IDX_10215 ON T_QUERY (LIST_QUERY_VIEW_TYPE_ID ASC);

CREATE UNIQUE INDEX SYS_IDX_SYS_PK_10098_10099 ON T_ARTIFACT_MODIFICATIONS_VIEW_TYPE (ARTIFACT_MODIFICATIONS_VIEW_TYPE_ID ASC);

CREATE UNIQUE INDEX SYS_IDX_SYS_PK_10130_10131 ON T_LAST_ID_NUMBER (ID ASC);

CREATE UNIQUE INDEX SYS_IDX_SYS_PK_10146_10147 ON T_ROOT_ARTIFACT_FOLDER (ID ASC);

CREATE UNIQUE INDEX SYS_IDX_SYS_PK_10157_10158 ON T_USER_LIST (ID ASC);

CREATE INDEX SYS_IDX_10169 ON T_ARTIFACT_CUSTOMFORM_VIEW_TYPE (ARTIFACT_CUSTOMFORM_VIEW_TYPE_ID ASC);

CREATE INDEX SYS_IDX_10227 ON T_USER_DATA_SHEET (USER ASC);

CREATE INDEX SYS_IDX_10189 ON T_ARTIFACT_MODIFICATIONS_VIEW_TYPE (ARTIFACT_MODIFICATIONS_VIEW_TYPE_ID ASC);

CREATE INDEX SYS_IDX_10219 ON T_ROOT_ARTIFACT_FOLDER (ARTIFACT_VERSION_ID ASC);

CREATE UNIQUE INDEX SYS_IDX_SYS_PK_10107_10108 ON T_ARTIFACT_TYPE (ID ASC);

CREATE INDEX SYS_IDX_10229 ON T_USER_LIST (ARTIFACT_VERSION_ID ASC);

CREATE UNIQUE INDEX SYS_IDX_SYS_PK_10120_10121 ON T_BACKUP_EVENT (ID ASC);

CREATE INDEX SYS_IDX_10221 ON T_ROOT_ARTIFACT_FOLDER (TYPE ASC);

CREATE INDEX SYS_IDX_10231 ON T_USER_LIST (TYPE ASC);

CREATE INDEX SYS_IDX_10195 ON T_ARTIFACT_TYPE (ARTIFACT_TYPE_GROUP_ID ASC);

CREATE UNIQUE INDEX SYS_IDX_SYS_PK_10092_10093 ON T_ARTIFACT_MENU (ID ASC);

CREATE UNIQUE INDEX SYS_IDX_SYS_PK_10133_10134 ON T_LIST_QUERY_VIEW_TYPE (LIST_QUERY_VIEW_TYPE_ID ASC);

CREATE UNIQUE INDEX SYS_IDX_SYS_PK_10065_10066 ON T_ACCESS_RIGHT (ID ASC);

CREATE INDEX SYS_IDX_10183 ON T_ARTIFACT_MENU (ARTIFACT_TYPE_ID ASC);

CREATE INDEX SYS_IDX_10207 ON T_LIST_QUERY_VIEW_TYPE (LIST_QUERY_VIEW_TYPE_ID ASC);

CREATE INDEX SYS_IDX_10185 ON T_ARTIFACT_MENU (ARTIFACT_VIEW_TYPE_ID ASC);

CREATE UNIQUE INDEX SYS_IDX_SYS_PK_10089_10090 ON T_ARTIFACT_LIST_VIEW_TYPE (ARTIFACT_LIST_VIEW_TYPE_ID ASC);

CREATE INDEX SYS_IDX_10187 ON T_ARTIFACT_MENU (COMMAND ASC);

CREATE UNIQUE INDEX SYS_IDX_SYS_PK_10135_10136 ON T_MODIFICATION (MODIFICATION_ID ASC);

CREATE UNIQUE INDEX SYS_IDX_SYS_PK_10074_10075 ON T_ARTIFACT_COMMENTS_VIEW_TYPE (ARTIFACT_COMMENTS_VIEW_TYPE_ID ASC);

CREATE INDEX SYS_IDX_10181 ON T_ARTIFACT_LIST_VIEW_TYPE (ARTIFACT_LIST_VIEW_TYPE_ID ASC);

ALTER TABLE T_ARTIFACT_TYPE_GROUP ADD CONSTRAINT SYS_REF_FK8093D7CA969BA531EC6ECD6C_10164 UNIQUE (ID);

ALTER TABLE T_USER ADD CONSTRAINT SYS_REF_FKEC6ECD6C1A4CBF82_10162 UNIQUE (ID);

ALTER TABLE T_ARTIFACT_TYPE ADD CONSTRAINT SYS_REF_FKD802DC327F51F874_10202 UNIQUE (ID);

ALTER TABLE T_ARTIFACT_TYPE_GROUP ADD CONSTRAINT SYS_PK_10110 PRIMARY KEY (ID);

ALTER TABLE T_QUERY ADD CONSTRAINT SYS_PK_10140 PRIMARY KEY (QUERY_ID);

ALTER TABLE T_HTML_ATTRIBUTE_FORMAT ADD CONSTRAINT SYS_PK_10125 PRIMARY KEY (HTML_ATTRIBUTE_FORMAT_ID);

ALTER TABLE T_ARTIFACT_VIEW_TYPE ADD CONSTRAINT SYS_REF_FK6A6310886D8C2ACD_10172 UNIQUE (ARTIFACT_VIEW_TYPE_ID);

ALTER TABLE T_ARTIFACT_VERSION ADD CONSTRAINT SYS_REF_FK12E6455D226E5739899F7590_10174 UNIQUE (ARTIFACT_VERSION_ID);

ALTER TABLE T_ARTIFACT_TYPE_GROUP ADD CONSTRAINT SYS_REF_FK2F51CCDC969BA531_10196 UNIQUE (ID);

ALTER TABLE T_USER ADD CONSTRAINT SYS_REF_FKE7FDE7D691331869_10198 UNIQUE (ID);

ALTER TABLE T_ARTIFACT_TYPE ADD CONSTRAINT SYS_REF_FK8093D7CA7F51F874_10204 UNIQUE (ID);

ALTER TABLE T_ARTIFACT_VIEW_TYPE ADD CONSTRAINT SYS_REF_FKFBC3055539EFBE0_10182 UNIQUE (ARTIFACT_VIEW_TYPE_ID);

ALTER TABLE T_ARTIFACT_VERSION ADD CONSTRAINT SYS_REF_FK12E6455D226E57392F4DEE40_10178 UNIQUE (ARTIFACT_VERSION_ID);

ALTER TABLE T_ARTIFACT_TYPE_GROUP ADD CONSTRAINT SYS_REF_FK8093D7CA969BA531_10206 UNIQUE (ID);

ALTER TABLE T_AUTO_IDENTIFIER ADD CONSTRAINT SYS_PK_10117 PRIMARY KEY (ID);

ALTER TABLE T_USER ADD CONSTRAINT SYS_REF_FKB64BA7FE61D44A_10212 UNIQUE (ID);

ALTER TABLE T_ARTIFACT_TYPE ADD CONSTRAINT SYS_REF_FK57793D927F51F874_10214 UNIQUE (ID);

ALTER TABLE T_ARTIFACT_LIST_VIEW_TYPE ADD CONSTRAINT SYS_PK_10089 PRIMARY KEY (ARTIFACT_LIST_VIEW_TYPE_ID);

ALTER TABLE T_ARTIFACT_VERSION ADD CONSTRAINT SYS_PK_10112 PRIMARY KEY (ARTIFACT_VERSION_ID);

ALTER TABLE T_ARTIFACT_COMMENTS_VIEW_TYPE ADD CONSTRAINT SYS_PK_10074 PRIMARY KEY (ARTIFACT_COMMENTS_VIEW_TYPE_ID);

ALTER TABLE T_DEFAULT_ACCESS_RIGHT ADD CONSTRAINT SYS_PK_10123 PRIMARY KEY (ID);

ALTER TABLE T_ARTIFACT_VIEW_TYPE ADD CONSTRAINT SYS_REF_FK2F4E5301EC5CDC59_10186 UNIQUE (ARTIFACT_VIEW_TYPE_ID);

ALTER TABLE T_ARTIFACT_VERSION ADD CONSTRAINT SYS_REF_FKB64BA7A0A46EF1_10210 UNIQUE (ARTIFACT_VERSION_ID);

ALTER TABLE T_USER ADD CONSTRAINT SYS_REF_FKF2C0AB732348BD3E_10228 UNIQUE (ID);

ALTER TABLE T_ARTIFACT_TYPE ADD CONSTRAINT SYS_REF_FK12E6455D5AC1ECDB899F7590ACB36929_10222 UNIQUE (ID);

ALTER TABLE T_APPLICATION_EVENT ADD CONSTRAINT SYS_PK_10068 PRIMARY KEY (ID);

ALTER TABLE T_ARTIFACT_ACCESSRIGHTS_VIEW_TYPE ADD CONSTRAINT SYS_PK_10071 PRIMARY KEY (ARTIFACT_ACCESSRIGHTS_VIEW_TYPE_ID);

ALTER TABLE T_ARTIFACT_FOLDER ADD CONSTRAINT SYS_PK_10083 PRIMARY KEY (ID);

ALTER TABLE T_ROOT_ARTIFACT_FOLDER ADD CONSTRAINT SYS_PK_10146 PRIMARY KEY (ID);

ALTER TABLE T_ARTIFACT_VIEW_TYPE ADD CONSTRAINT SYS_REF_FKC4B98BAAC835DE81_10190 UNIQUE (ARTIFACT_VIEW_TYPE_ID);

ALTER TABLE T_ARTIFACT_VERSION ADD CONSTRAINT SYS_REF_FK12E6455D226E5739899F7590ACB36929_10220 UNIQUE (ARTIFACT_VERSION_ID);

ALTER TABLE T_USER ADD CONSTRAINT SYS_PK_10149 PRIMARY KEY (ID);

ALTER TABLE T_ARTIFACT_TYPE ADD CONSTRAINT SYS_REF_FK12E6455D5AC1ECDBF2C0AB73_10226 UNIQUE (ID);

ALTER TABLE T_PROPERTY_DEFINITION ADD CONSTRAINT SYS_PK_10138 PRIMARY KEY (ID);

ALTER TABLE T_ARTIFACT_PROPERTY_VIEW_TYPE ADD CONSTRAINT SYS_PK_10104 PRIMARY KEY (RELATED_ARTIFACTS_VIEW_TYPE_ID);

ALTER TABLE T_ARTIFACT_VIEW_TYPE ADD CONSTRAINT SYS_REF_FKE810D6805C3C26EB_10192 UNIQUE (ARTIFACT_VIEW_TYPE_ID);

ALTER TABLE T_USER_LIST ADD CONSTRAINT SYS_PK_10157 PRIMARY KEY (ID);

ALTER TABLE T_ARTIFACT_VERSION ADD CONSTRAINT SYS_REF_FK12E6455D226E5739F2C0AB73_10224 UNIQUE (ARTIFACT_VERSION_ID);

ALTER TABLE T_ARTIFACT_TYPE ADD CONSTRAINT SYS_REF_FK12E6455D5AC1ECDB2F4DEE403E5FC667_10232 UNIQUE (ID);

ALTER TABLE T_ARTIFACT_TYPE ADD CONSTRAINT SYS_REF_FK8093D7CA7F51F874EC6ECD6C_10160 UNIQUE (ID);

ALTER TABLE T_ARTIFACT_MENU_COMMAND ADD CONSTRAINT SYS_PK_10095 PRIMARY KEY (ID);

ALTER TABLE T_MODIFICATION ADD CONSTRAINT SYS_PK_10135 PRIMARY KEY (MODIFICATION_ID);

ALTER TABLE T_ARTIFACT_VIEW_TYPE ADD CONSTRAINT SYS_REF_FKD4A0F0CC8BCF203E_10194 UNIQUE (ARTIFACT_VIEW_TYPE_ID);

ALTER TABLE T_USER_DATA_SHEET ADD CONSTRAINT SYS_PK_10152 PRIMARY KEY (ID);

ALTER TABLE T_ARTIFACT_VERSION ADD CONSTRAINT SYS_REF_FK12E6455D226E57392F4DEE403E5FC667_10230 UNIQUE (ARTIFACT_VERSION_ID);

ALTER TABLE T_LAST_ID_NUMBER ADD CONSTRAINT SYS_PK_10130 PRIMARY KEY (ID);

ALTER TABLE T_ARTIFACT_TYPE ADD CONSTRAINT SYS_REF_FK12E6455D5AC1ECDB899F7590_10176 UNIQUE (ID);

ALTER TABLE T_ARTIFACT_TYPE ADD CONSTRAINT SYS_PK_10107 PRIMARY KEY (ID);

ALTER TABLE T_ARTIFACT_VIEW_TYPE ADD CONSTRAINT SYS_REF_FK494AF274B28AE64_10208 UNIQUE (ARTIFACT_VIEW_TYPE_ID);

ALTER TABLE T_ARTIFACT_MENU_COMMAND ADD CONSTRAINT SYS_REF_FK2F4E5301E70FC7F0_10188 UNIQUE (ID);

ALTER TABLE T_ARTIFACT_VIEW_TYPE ADD CONSTRAINT SYS_REF_FK46E97EB22D5A1463_10166 UNIQUE (ARTIFACT_VIEW_TYPE_ID);

ALTER TABLE T_LIST_QUERY_VIEW_TYPE ADD CONSTRAINT SYS_REF_FK244F4FDDD6F2412_10216 UNIQUE (LIST_QUERY_VIEW_TYPE_ID);

ALTER TABLE T_ARTIFACT_PRINT_VIEW_TYPE ADD CONSTRAINT SYS_PK_10101 PRIMARY KEY (ARTIFACT_PRINT_VIEW_TYPE_ID);

ALTER TABLE T_ARTIFACT_EDITABLETEXT_VIEW_TYPE ADD CONSTRAINT SYS_PK_10080 PRIMARY KEY (ARTIFACT_EDITABLETEXT_VIEW_TYPE_ID);

ALTER TABLE T_BACKUP_EVENT ADD CONSTRAINT SYS_PK_10120 PRIMARY KEY (ID);

ALTER TABLE T_ARTIFACT_TYPE ADD CONSTRAINT SYS_REF_FK12E6455D5AC1ECDB2F4DEE40_10180 UNIQUE (ID);

ALTER TABLE T_ARTIFACT_MENU ADD CONSTRAINT SYS_PK_10092 PRIMARY KEY (ID);

ALTER TABLE T_ARTIFACT_LIST ADD CONSTRAINT SYS_PK_10086 PRIMARY KEY (ID);

ALTER TABLE T_MODIFICATION ADD CONSTRAINT SYS_REF_FKE7FDE7D6FAA49207_10200 UNIQUE (MODIFICATION_ID);

ALTER TABLE T_LIST_QUERY_VIEW_TYPE ADD CONSTRAINT SYS_PK_10133 PRIMARY KEY (LIST_QUERY_VIEW_TYPE_ID);

ALTER TABLE T_ACCESS_RIGHT ADD CONSTRAINT SYS_PK_10065 PRIMARY KEY (ID);

ALTER TABLE T_ARTIFACT_VIEW_TYPE ADD CONSTRAINT SYS_REF_FKF8C766F78BCF203E_10218 UNIQUE (ARTIFACT_VIEW_TYPE_ID);

ALTER TABLE T_ARTIFACT_VIEW_TYPE ADD CONSTRAINT SYS_REF_FKDF1C962B144B08CA_10168 UNIQUE (ARTIFACT_VIEW_TYPE_ID);

ALTER TABLE T_RELATED_ARTIFACTS_VIEW_TYPE ADD CONSTRAINT SYS_PK_10143 PRIMARY KEY (RELATED_ARTIFACTS_VIEW_TYPE_ID);

ALTER TABLE T_ARTIFACT_TYPE ADD CONSTRAINT SYS_REF_FK2F4E53017F51F874_10184 UNIQUE (ID);

ALTER TABLE T_ARTIFACT_VIEW_TYPE ADD CONSTRAINT SYS_PK_10114 PRIMARY KEY (ARTIFACT_VIEW_TYPE_ID);

ALTER TABLE T_ARTIFACT_MODIFICATIONS_VIEW_TYPE ADD CONSTRAINT SYS_PK_10098 PRIMARY KEY (ARTIFACT_MODIFICATIONS_VIEW_TYPE_ID);

ALTER TABLE T_ARTIFACT_CUSTOMFORM_VIEW_TYPE ADD CONSTRAINT SYS_PK_10077 PRIMARY KEY (ARTIFACT_CUSTOMFORM_VIEW_TYPE_ID);

ALTER TABLE T_ARTIFACT_VIEW_TYPE ADD CONSTRAINT SYS_REF_FKBC96AE2C3BDD07E9_10170 UNIQUE (ARTIFACT_VIEW_TYPE_ID);

ALTER TABLE T_ARTIFACT_PROPERTY_VIEW_TYPE ADD CONSTRAINT FKD4A0F0CC8BCF203E FOREIGN KEY (RELATED_ARTIFACTS_VIEW_TYPE_ID)
	REFERENCES T_ARTIFACT_VIEW_TYPE (ARTIFACT_VIEW_TYPE_ID);

ALTER TABLE T_ARTIFACT_MENU ADD CONSTRAINT FK2F4E53017F51F874 FOREIGN KEY (ARTIFACT_TYPE_ID)
	REFERENCES T_ARTIFACT_TYPE (ID);

ALTER TABLE T_ARTIFACT_FOLDER ADD CONSTRAINT FK12E6455D5AC1ECDB899F7590 FOREIGN KEY (TYPE)
	REFERENCES T_ARTIFACT_TYPE (ID);

ALTER TABLE T_ACCESS_RIGHT ADD CONSTRAINT FK8093D7CA969BA531EC6ECD6C FOREIGN KEY (ARTIFACT_TYPE_GROUP_ID)
	REFERENCES T_ARTIFACT_TYPE_GROUP (ID);

ALTER TABLE T_ROOT_ARTIFACT_FOLDER ADD CONSTRAINT FK12E6455D5AC1ECDB899F7590ACB36929 FOREIGN KEY (TYPE)
	REFERENCES T_ARTIFACT_TYPE (ID);

ALTER TABLE T_ARTIFACT_VERSION ADD CONSTRAINT FKE7FDE7D691331869 FOREIGN KEY (RESPONSIBLE)
	REFERENCES T_USER (ID);

ALTER TABLE T_DEFAULT_ACCESS_RIGHT ADD CONSTRAINT FK8093D7CA969BA531 FOREIGN KEY (ARTIFACT_TYPE_GROUP_ID)
	REFERENCES T_ARTIFACT_TYPE_GROUP (ID);

ALTER TABLE T_USER_LIST ADD CONSTRAINT FK12E6455D5AC1ECDB2F4DEE403E5FC667 FOREIGN KEY (TYPE)
	REFERENCES T_ARTIFACT_TYPE (ID);

ALTER TABLE T_ARTIFACT_MENU ADD CONSTRAINT FK2F4E5301EC5CDC59 FOREIGN KEY (ARTIFACT_VIEW_TYPE_ID)
	REFERENCES T_ARTIFACT_VIEW_TYPE (ARTIFACT_VIEW_TYPE_ID);

ALTER TABLE T_ARTIFACT_VIEW_TYPE ADD CONSTRAINT FKD802DC327F51F874 FOREIGN KEY (ARTIFACT_TYPE_ID)
	REFERENCES T_ARTIFACT_TYPE (ID);

ALTER TABLE T_ARTIFACT_FOLDER ADD CONSTRAINT FK12E6455D226E5739899F7590 FOREIGN KEY (ARTIFACT_VERSION_ID)
	REFERENCES T_ARTIFACT_VERSION (ARTIFACT_VERSION_ID);

ALTER TABLE T_ARTIFACT_PRINT_VIEW_TYPE ADD CONSTRAINT FKE810D6805C3C26EB FOREIGN KEY (ARTIFACT_PRINT_VIEW_TYPE_ID)
	REFERENCES T_ARTIFACT_VIEW_TYPE (ARTIFACT_VIEW_TYPE_ID);

ALTER TABLE T_ROOT_ARTIFACT_FOLDER ADD CONSTRAINT FK12E6455D226E5739899F7590ACB36929 FOREIGN KEY (ARTIFACT_VERSION_ID)
	REFERENCES T_ARTIFACT_VERSION (ARTIFACT_VERSION_ID);

ALTER TABLE T_ARTIFACT_EDITABLETEXT_VIEW_TYPE ADD CONSTRAINT FK6A6310886D8C2ACD FOREIGN KEY (ARTIFACT_EDITABLETEXT_VIEW_TYPE_ID)
	REFERENCES T_ARTIFACT_VIEW_TYPE (ARTIFACT_VIEW_TYPE_ID);

ALTER TABLE T_USER_LIST ADD CONSTRAINT FK12E6455D226E57392F4DEE403E5FC667 FOREIGN KEY (ARTIFACT_VERSION_ID)
	REFERENCES T_ARTIFACT_VERSION (ARTIFACT_VERSION_ID);

ALTER TABLE T_RELATED_ARTIFACTS_VIEW_TYPE ADD CONSTRAINT FKF8C766F78BCF203E FOREIGN KEY (RELATED_ARTIFACTS_VIEW_TYPE_ID)
	REFERENCES T_ARTIFACT_VIEW_TYPE (ARTIFACT_VIEW_TYPE_ID);

ALTER TABLE T_MODIFICATION ADD CONSTRAINT FKB64BA7A0A46EF1 FOREIGN KEY (TARGETVERSION)
	REFERENCES T_ARTIFACT_VERSION (ARTIFACT_VERSION_ID);

ALTER TABLE T_USER_DATA_SHEET ADD CONSTRAINT FK12E6455D5AC1ECDBF2C0AB73 FOREIGN KEY (TYPE)
	REFERENCES T_ARTIFACT_TYPE (ID);

ALTER TABLE T_ARTIFACT_CUSTOMFORM_VIEW_TYPE ADD CONSTRAINT FKBC96AE2C3BDD07E9 FOREIGN KEY (ARTIFACT_CUSTOMFORM_VIEW_TYPE_ID)
	REFERENCES T_ARTIFACT_VIEW_TYPE (ARTIFACT_VIEW_TYPE_ID);

ALTER TABLE T_ARTIFACT_LIST ADD CONSTRAINT FK12E6455D5AC1ECDB2F4DEE40 FOREIGN KEY (TYPE)
	REFERENCES T_ARTIFACT_TYPE (ID);

ALTER TABLE T_ARTIFACT_MODIFICATIONS_VIEW_TYPE ADD CONSTRAINT FKC4B98BAAC835DE81 FOREIGN KEY (ARTIFACT_MODIFICATIONS_VIEW_TYPE_ID)
	REFERENCES T_ARTIFACT_VIEW_TYPE (ARTIFACT_VIEW_TYPE_ID);

ALTER TABLE T_ACCESS_RIGHT ADD CONSTRAINT FKEC6ECD6C1A4CBF82 FOREIGN KEY (USER_ID)
	REFERENCES T_USER (ID);

ALTER TABLE T_QUERY ADD CONSTRAINT FK244F4FDDD6F2412 FOREIGN KEY (LIST_QUERY_VIEW_TYPE_ID)
	REFERENCES T_LIST_QUERY_VIEW_TYPE (LIST_QUERY_VIEW_TYPE_ID);

ALTER TABLE T_ARTIFACT_TYPE ADD CONSTRAINT FK2F51CCDC969BA531 FOREIGN KEY (ARTIFACT_TYPE_GROUP_ID)
	REFERENCES T_ARTIFACT_TYPE_GROUP (ID);

ALTER TABLE T_ARTIFACT_MENU ADD CONSTRAINT FK2F4E5301E70FC7F0 FOREIGN KEY (COMMAND)
	REFERENCES T_ARTIFACT_MENU_COMMAND (ID);

ALTER TABLE T_MODIFICATION ADD CONSTRAINT FKB64BA7FE61D44A FOREIGN KEY (MODIFIER)
	REFERENCES T_USER (ID);

ALTER TABLE T_ARTIFACT_VERSION ADD CONSTRAINT FKE7FDE7D6FAA49207 FOREIGN KEY (NEXTMODIFICATION)
	REFERENCES T_MODIFICATION (MODIFICATION_ID);

ALTER TABLE T_USER_DATA_SHEET ADD CONSTRAINT FK12E6455D226E5739F2C0AB73 FOREIGN KEY (ARTIFACT_VERSION_ID)
	REFERENCES T_ARTIFACT_VERSION (ARTIFACT_VERSION_ID);

ALTER TABLE T_ARTIFACT_LIST ADD CONSTRAINT FK12E6455D226E57392F4DEE40 FOREIGN KEY (ARTIFACT_VERSION_ID)
	REFERENCES T_ARTIFACT_VERSION (ARTIFACT_VERSION_ID);

ALTER TABLE T_LIST_QUERY_VIEW_TYPE ADD CONSTRAINT FK494AF274B28AE64 FOREIGN KEY (LIST_QUERY_VIEW_TYPE_ID)
	REFERENCES T_ARTIFACT_VIEW_TYPE (ARTIFACT_VIEW_TYPE_ID);

ALTER TABLE T_ACCESS_RIGHT ADD CONSTRAINT FK8093D7CA7F51F874EC6ECD6C FOREIGN KEY (ARTIFACT_TYPE_ID)
	REFERENCES T_ARTIFACT_TYPE (ID);

ALTER TABLE T_ARTIFACT_LIST_VIEW_TYPE ADD CONSTRAINT FKFBC3055539EFBE0 FOREIGN KEY (ARTIFACT_LIST_VIEW_TYPE_ID)
	REFERENCES T_ARTIFACT_VIEW_TYPE (ARTIFACT_VIEW_TYPE_ID);

ALTER TABLE T_ARTIFACT_COMMENTS_VIEW_TYPE ADD CONSTRAINT FKDF1C962B144B08CA FOREIGN KEY (ARTIFACT_COMMENTS_VIEW_TYPE_ID)
	REFERENCES T_ARTIFACT_VIEW_TYPE (ARTIFACT_VIEW_TYPE_ID);

ALTER TABLE T_USER_DATA_SHEET ADD CONSTRAINT FKF2C0AB732348BD3E FOREIGN KEY (USER)
	REFERENCES T_USER (ID);

ALTER TABLE T_ARTIFACT_ACCESSRIGHTS_VIEW_TYPE ADD CONSTRAINT FK46E97EB22D5A1463 FOREIGN KEY (ARTIFACT_ACCESSRIGHTS_VIEW_TYPE_ID)
	REFERENCES T_ARTIFACT_VIEW_TYPE (ARTIFACT_VIEW_TYPE_ID);

ALTER TABLE T_DEFAULT_ACCESS_RIGHT ADD CONSTRAINT FK8093D7CA7F51F874 FOREIGN KEY (ARTIFACT_TYPE_ID)
	REFERENCES T_ARTIFACT_TYPE (ID);

ALTER TABLE T_PROPERTY_DEFINITION ADD CONSTRAINT FK57793D927F51F874 FOREIGN KEY (ARTIFACT_TYPE_ID)
	REFERENCES T_ARTIFACT_TYPE (ID);

